# Copyright 2026 Scion Frontiers & Antigravity - Rareș Cristea
# Universal App Store Connect Distribution Metadata & Compliance Engine
# Applicable to ANY iOS, iPadOS, macOS, watchOS, or visionOS project.

from __future__ import annotations
from dataclasses import dataclass, field
import json
import logging
import os
import re
from typing import Any, Dict, List, Optional, Tuple

logger = logging.getLogger("core.apple.distribution")

@dataclass
class AppStoreMetadata:
    # 1. App Information - Localizable Information
    app_name: str
    app_subtitle: str  # max 30 chars
    
    # 1. App Information - General Information
    bundle_id: str
    sku: str
    apple_id: str
    primary_category: str
    secondary_category: Optional[str]
    content_rights: str  # Yes/No declaration + explanation
    license_agreement: str  # Apple Standard EULA or Custom
    age_ratings: Dict[str, Any]
    app_encryption_doc: str  # max 300 chars
    app_store_regulations_url: str  # EU GPSR Labels and Markings URL
    production_server_url: str
    sandbox_server_url: str
    
    # 2. App Review Information
    app_review_notes: str  # max 4000 chars
    app_review_attachment_guidance: str
    demo_account_credentials: Dict[str, str]
    
    # 3. Distribution Section
    promotional_text: str  # max 170 chars
    description: str  # max 4000 chars
    keywords: str  # max 100 chars
    support_url: str
    marketing_url: str
    routing_app_coverage: str  # .geojson or N/A
    regulated_medical_devices: str  # Yes/No declaration
    app_purpose: str
    beta_app_description: str  # max 4000 chars

    def validate_constraints(self) -> List[str]:
        """Validates all strict Apple App Store Connect character limits."""
        errors = []
        if len(self.app_name) > 30:
            errors.append(f"App Name exceeds 30 characters: {len(self.app_name)} chars")
        if len(self.app_subtitle) > 30:
            errors.append(f"App Subtitle exceeds 30 characters: {len(self.app_subtitle)} chars")
        if len(self.promotional_text) > 170:
            errors.append(f"Promotional Text exceeds 170 characters: {len(self.promotional_text)} chars")
        if len(self.description) > 4000:
            errors.append(f"Description exceeds 4000 characters: {len(self.description)} chars")
        if len(self.keywords) > 100:
            errors.append(f"Keywords exceed 100 characters: {len(self.keywords)} chars")
        if len(self.app_review_notes) > 4000:
            errors.append(f"App Review Notes exceed 4000 characters: {len(self.app_review_notes)} chars")
        if len(self.app_encryption_doc) > 300:
            errors.append(f"App Encryption Doc exceeds 300 characters: {len(self.app_encryption_doc)} chars")
        if len(self.beta_app_description) > 4000:
            errors.append(f"Beta App Description exceeds 4000 characters: {len(self.beta_app_description)} chars")
        return errors

    def to_markdown(self) -> str:
        """Renders the comprehensive distribution document in English."""
        age_details = "\n".join([f"  - **{k}**: {v}" for k, v in self.age_ratings.get('details', {}).items()])
        return f"""# App Store Connect Distribution Specification

Generated by **Apple Developer Compliance Suite**  
Target App: **{self.app_name}** | Bundle ID: `{self.bundle_id}` | Primary Category: **{self.primary_category}**

---

## 1. App Information

### Localizable Information
* **App Name**: {self.app_name} `({len(self.app_name)}/30 chars)`
* **App Subtitle**: {self.app_subtitle} `({len(self.app_subtitle)}/30 chars)`

### General Information
* **Bundle ID**: `{self.bundle_id}`
* **SKU**: `{self.sku}`
* **APPLE ID**: `{self.apple_id}`
* **Category (Primary)**: {self.primary_category}
* **Category (Secondary)**: {self.secondary_category or "None"}

### Content Rights
* **Does your app contain, show, or access third-party content?**
  > **{self.content_rights}**

### License Agreement
* **EULA Selection**: {self.license_agreement}
* Apple Standard EULA applies to all countries and regions unless custom terms are specified.

### Age Ratings
* **Rating Assigned**: **{self.age_ratings.get('rating', '4+')}**
* **Questionnaire Responses**:
{age_details}

### App Encryption Documentation
* **Declaration**: {self.app_encryption_doc} `({len(self.app_encryption_doc)}/300 chars)`
* **ITSAppUsesNonExemptEncryption**: `NO` (Standard HTTPS/TLS encryption exempt under Export Administration Regulations EAR 740.17(b)(1)).

### App Store Regulations & Permits (EU GPSR)
* **Labels and Markings URL**: [{self.app_store_regulations_url}]({self.app_store_regulations_url})

### App Store Server Notifications
* **Production Server URL**: `{self.production_server_url}`
* **Sandbox Server URL**: `{self.sandbox_server_url}`

---

## 2. App Review Information

### App Review Notes `({len(self.app_review_notes)}/4000 chars)`
```
{self.app_review_notes}
```

### Reviewer Credentials & Test Accounts
* **Username / Email**: `{self.demo_account_credentials.get('username', 'demo_reviewer@appreview.apple')}`
* **Password**: `{self.demo_account_credentials.get('password', 'ReviewerPass2026!')}`
* **2FA / OTP Instructions**: `{self.demo_account_credentials.get('otp_instructions', '2FA is disabled or bypassed for App Store Review test accounts.')}`

### App Review Information / Attachment
* **Allowed Extensions**: `.pdf, .doc, .docx, .rtf, .pages, .xls, .xlsx, .numbers, .zip, .rar, .plist, .crash, .jpg, .png, .mp4, .avi`
* **Included / Suggested Attachment**:
  > {self.app_review_attachment_guidance}

---

## 3. Distribution & Marketing

### Promotional Text `({len(self.promotional_text)}/170 chars)`
> {self.promotional_text}

### Description `({len(self.description)}/4000 chars)`
```
{self.description}
```

### Keywords `({len(self.keywords)}/100 chars)`
`{self.keywords}`

### URLs
* **Support URL**: [{self.support_url}]({self.support_url})
* **Marketing URL**: [{self.marketing_url}]({self.marketing_url})

### Routing App Coverage File
* **Coverage**: {self.routing_app_coverage}

### Regulated Medical Devices
* **Declaration**: {self.regulated_medical_devices}

### App Purpose
* **Core Value Proposition**:
  {self.app_purpose}

### Beta App Description (TestFlight) `({len(self.beta_app_description)}/4000 chars)`
```
{self.beta_app_description}
```

---
*Auto-generated by Universal Apple Developer Suite (Scion Frontiers & Antigravity).*
"""


class AppStoreDistributionGenerator:
    """
    Universal App Store Connect Distribution Analyzer & Manifest Generator.
    Analyzes ANY iOS, iPadOS, macOS, watchOS, or visionOS project and automatically
    builds valid, constraint-checked metadata in English.
    """

    @classmethod
    def analyze_and_generate(
        cls,
        project_dir: str,
        github_repo_url: Optional[str] = None,
        custom_sku: Optional[str] = None,
        output_file: Optional[str] = None,
    ) -> Tuple[AppStoreMetadata, str]:
        abs_path = os.path.abspath(os.path.expanduser(project_dir))

        # 1. Universal Identity Extraction
        app_name, bundle_id = cls._discover_identity(abs_path)
        
        # 2. Deep Technology & Domain Discovery
        analysis = cls._deep_scan_project(abs_path, app_name)
        
        # 3. Dynamic URLs
        repo_url = github_repo_url or f"https://github.com/developer/{app_name.lower().replace(' ', '-')}"
        sku = custom_sku or f"SKU-{re.sub(r'[^a-zA-Z0-9]', '', app_name).upper()}-2026"
        apple_id = analysis.get("apple_id", "6814920482")

        support_url = f"{repo_url}/issues"
        marketing_url = f"{repo_url}#readme"
        production_server_url = f"{repo_url}/api/v1/app-store-notifications"
        sandbox_server_url = f"{repo_url}/api/v1/sandbox/app-store-notifications"
        regulations_url = f"{repo_url}/blob/main/LEGAL_AND_GPSR_COMPLIANCE.md"

        # 4. Strict Constraint Generation
        subtitle = analysis["subtitle"][:30]
        promo_text = analysis["promotional_text"][:170]
        keywords = analysis["keywords"][:100]
        description = analysis["description"][:4000]
        review_notes = analysis["review_notes"][:4000]
        beta_desc = analysis["beta_description"][:4000]
        encryption_doc = analysis.get("app_encryption_doc", analysis.get("encryption_doc", ""))[:300]

        metadata = AppStoreMetadata(
            app_name=app_name[:30],
            app_subtitle=subtitle,
            bundle_id=bundle_id,
            sku=sku,
            apple_id=apple_id,
            primary_category=analysis["primary_category"],
            secondary_category=analysis.get("secondary_category"),
            content_rights=analysis["content_rights"],
            license_agreement=analysis["license_agreement"],
            age_ratings=analysis["age_ratings"],
            app_encryption_doc=encryption_doc,
            app_store_regulations_url=regulations_url,
            production_server_url=production_server_url,
            sandbox_server_url=sandbox_server_url,
            app_review_notes=review_notes,
            app_review_attachment_guidance=analysis["attachment_guidance"],
            demo_account_credentials=analysis["demo_credentials"],
            promotional_text=promo_text,
            description=description,
            keywords=keywords,
            support_url=support_url,
            marketing_url=marketing_url,
            routing_app_coverage=analysis["routing_coverage"],
            regulated_medical_devices=analysis["regulated_medical_devices"],
            app_purpose=analysis["app_purpose"],
            beta_app_description=beta_desc
        )

        # Validate constraints
        validation_errors = metadata.validate_constraints()
        if validation_errors:
            logger.warning(f"Validation warnings: {validation_errors}")

        md_content = metadata.to_markdown()

        if output_file:
            target_out = os.path.abspath(output_file)
            os.makedirs(os.path.dirname(target_out), exist_ok=True)
            with open(target_out, "w", encoding="utf-8") as f:
                f.write(md_content)
            logger.info(f"Universal App Store Connect distribution written to: {target_out}")

        return metadata, md_content

    # -------------------------------------------------------------
    # Universal Project Discovery & Signal Parsing
    # -------------------------------------------------------------
    @classmethod
    def _discover_identity(cls, project_dir: str) -> Tuple[str, str]:
        """Universally resolves App Name and Bundle Identifier from Xcode, SPM, or files."""
        app_name = None
        bundle_id = None

        # 1. Search Info.plist files
        for root, _, files in os.walk(project_dir):
            if "Info.plist" in files:
                plist_file = os.path.join(root, "Info.plist")
                try:
                    with open(plist_file, "r", encoding="utf-8", errors="ignore") as f:
                        text = f.read()
                    
                    # Display name or Bundle Name
                    m_disp = re.search(r"<key>CFBundleDisplayName</key>\s*<string>([^<]+)</string>", text)
                    m_name = re.search(r"<key>CFBundleName</key>\s*<string>([^<]+)</string>", text)
                    m_bid = re.search(r"<key>CFBundleIdentifier</key>\s*<string>([^<]+)</string>", text)

                    if m_disp and not m_disp.group(1).startswith("$"):
                        app_name = m_disp.group(1)
                    elif m_name and not m_name.group(1).startswith("$") and not app_name:
                        app_name = m_name.group(1)

                    if m_bid and not m_bid.group(1).startswith("$"):
                        bundle_id = m_bid.group(1)
                except Exception:
                    pass

        # 2. Search project.pbxproj
        if not app_name or not bundle_id:
            for root, _, files in os.walk(project_dir):
                if "project.pbxproj" in files:
                    pbx_file = os.path.join(root, "project.pbxproj")
                    try:
                        with open(pbx_file, "r", encoding="utf-8", errors="ignore") as f:
                            pbx = f.read()
                        if not app_name:
                            p_match = re.search(r"PRODUCT_NAME\s*=\s*[\"']?([^;\"']+)[\"']?;", pbx)
                            if p_match and not p_match.group(1).startswith("$"):
                                app_name = p_match.group(1).strip()
                        if not bundle_id:
                            bid_match = re.search(r"PRODUCT_BUNDLE_IDENTIFIER\s*=\s*[\"']?([^;\"']+)[\"']?;", pbx)
                            if bid_match and not bid_match.group(1).startswith("$"):
                                bundle_id = bid_match.group(1).strip()
                    except Exception:
                        pass

        # 3. Search Package.swift
        if not app_name:
            pkg_file = os.path.join(project_dir, "Package.swift")
            if os.path.exists(pkg_file):
                try:
                    with open(pkg_file, "r", encoding="utf-8", errors="ignore") as f:
                        pkg_text = f.read()
                    name_m = re.search(r'name:\s*"([^"]+)"', pkg_text)
                    if name_m:
                        app_name = name_m.group(1)
                except Exception:
                    pass

        # Fallback to directory name
        if not app_name:
            dir_base = os.path.basename(os.path.abspath(project_dir))
            clean_name = re.sub(r"[^a-zA-Z0-9\s_-]", "", dir_base).replace("-", " ").replace("_", " ").title()
            app_name = clean_name.strip() or "Universal Application"

        if not bundle_id:
            clean_slug = re.sub(r"[^a-z0-9]", "", app_name.lower())
            bundle_id = f"com.developer.{clean_slug}"

        return app_name, bundle_id

    @classmethod
    def _deep_scan_project(cls, project_dir: str, app_name: str) -> Dict[str, Any]:
        """Universally scans project source code and packages to determine domain and rules."""
        stats = {
            "has_health": False,
            "has_medical": False,
            "has_map_routing": False,
            "has_ai": False,
            "has_camera": False,
            "has_audio": False,
            "has_game": False,
            "has_finance": False,
            "has_auth": False,
            "has_third_party_content": False,
            "has_unrestricted_web": False,
            "has_custom_crypto": False,
            "sample_features": []
        }

        # Scan code files
        code_exts = (".swift", ".m", ".h", ".kt", ".dart", ".js", ".ts", ".py", ".cpp")
        files_scanned = 0
        feature_keywords = set()

        for root, _, files in os.walk(project_dir):
            if any(p in root for p in [".git", "DerivedData", ".build", "node_modules"]):
                continue
            for f in files:
                if f.endswith(code_exts):
                    files_scanned += 1
                    file_path = os.path.join(root, f)
                    try:
                        with open(file_path, "r", encoding="utf-8", errors="ignore") as file_obj:
                            content = file_obj.read()

                        # Health & Medical
                        if "HealthKit" in content or "HKHealthStore" in content:
                            stats["has_health"] = True
                            feature_keywords.add("Health tracking")
                        if any(k in content for k in ["diagnosis", "treatment", "clinical", "vitalSigns", "CareKit", "ResearchKit"]):
                            stats["has_medical"] = True
                            feature_keywords.add("Medical data analysis")

                        # Maps & Navigation
                        if "MKDirections" in content or "turnByTurn" in content or "navigating" in content:
                            stats["has_map_routing"] = True
                            feature_keywords.add("Route navigation")

                        # AI / Machine Learning
                        if any(k in content for k in ["CoreML", "CreateML", "MLX", "llama", "PyTorch", "OpenAI", "Anthropic", "model_infer"]):
                            stats["has_ai"] = True
                            feature_keywords.add("Intelligent AI workflows")

                        # Gaming
                        if any(k in content for k in ["SpriteKit", "SceneKit", "GameplayKit", "SKScene", "SCNScene"]):
                            stats["has_game"] = True
                            feature_keywords.add("Interactive gameplay")

                        # Finance
                        if any(k in content for k in ["crypto", "bitcoin", "wallet", "banking", "Plaid", "transaction"]):
                            stats["has_finance"] = True
                            feature_keywords.add("Financial management")

                        # Authentication
                        if any(k in content for k in ["AuthenticationServices", "ASAuthorizationAppleIDButton", "login", "signIn", "LocalAuthentication"]):
                            stats["has_auth"] = True

                        # Web & Third-party content
                        if "WKWebView" in content:
                            stats["has_unrestricted_web"] = True
                        if any(k in content for k in ["youtube.com", "spotify.com", "vimeo.com", "soundcloud.com"]):
                            stats["has_third_party_content"] = True

                        # Custom cryptography
                        if "CommonCrypto" in content and any(k in content for k in ["CCCryptorCreate", "SecKeyCreateRandomKey", "EVP_Cipher"]):
                            stats["has_custom_crypto"] = True

                    except Exception:
                        pass

        stats["sample_features"] = list(feature_keywords)

        # Determine Primary and Secondary Category universally
        if stats["has_game"]:
            primary_cat = "Games"
            secondary_cat = "Entertainment"
        elif stats["has_medical"]:
            primary_cat = "Medical"
            secondary_cat = "Health & Fitness"
        elif stats["has_health"]:
            primary_cat = "Health & Fitness"
            secondary_cat = "Lifestyle"
        elif stats["has_map_routing"]:
            primary_cat = "Navigation"
            secondary_cat = "Travel"
        elif stats["has_finance"]:
            primary_cat = "Finance"
            secondary_cat = "Business"
        elif stats["has_ai"]:
            primary_cat = "Developer Tools"
            secondary_cat = "Productivity"
        else:
            primary_cat = "Productivity"
            secondary_cat = "Utilities"

        # Content Rights declaration
        if stats["has_third_party_content"]:
            content_rights = "Yes, it contains, shows, or accesses third-party content, and I have the necessary rights and licensing agreements to distribute this content."
        else:
            content_rights = "No, it does not contain, show, or access third-party content without ownership or license. All content, assets, and source code are first-party or licensed under standard open source and proprietary terms."

        # Age Ratings Questionnaire
        age_rating = "4+"
        if stats["has_unrestricted_web"]:
            age_rating = "17+"  # Apple Guideline for unmoderated web browsing
        elif stats["has_medical"]:
            age_rating = "12+"  # Medical/treatment info guideline

        age_details = {
            "Violence (Cartoon, Fantasy, Realistic)": "Frequent" if stats["has_game"] else "None",
            "Profanity or Crude Humor": "None",
            "Medical or Treatment Information": "Frequent" if stats["has_medical"] else ("Infrequent" if stats["has_health"] else "None"),
            "Alcohol, Tobacco, or Drug Use": "None",
            "Contests or Gambling": "None",
            "Unrestricted Web Access": "Yes" if stats["has_unrestricted_web"] else "No",
            "Made for Kids": "No",
        }

        # App Encryption Documentation (<= 300 chars)
        if stats["has_custom_crypto"]:
            encryption_doc = "App implements standard cryptographic protocols and HTTPS/TLS for secure client-server communication. Complies with US EAR section 740.17 exemptions."[:300]
        else:
            encryption_doc = "App uses standard HTTPS (TLS 1.3/AES-256) for secure network communication. Exempt from encryption documentation under US EAR section 740.17(b)(1)."[:300]

        # Regulated Medical Device Declaration
        if stats["has_medical"]:
            reg_medical = "Yes, application provides health or medical insights. Please review the attached clinical declaration and non-diagnostic disclaimer."
        else:
            reg_medical = "No, this app does not function as a regulated medical device and is not subject to FDA or EU MDR regulations."

        # Routing Coverage (.geojson)
        if stats["has_map_routing"]:
            routing_coverage = "Included .geojson MultiPolygon file specifying supported geographical territories for turn-by-turn navigation."
        else:
            routing_coverage = "Not Applicable. The application does not provide turn-by-turn routing or geographical navigation."

        # Subtitle (<= 30 chars)
        subtitle = f"{primary_cat} & Workflows"
        if stats["has_ai"]:
            subtitle = f"AI {primary_cat} & Automation"
        elif stats["has_health"]:
            subtitle = "Health, Fitness & Activity"
        elif stats["has_finance"]:
            subtitle = "Smart Budget & Finance"
        elif stats["has_game"]:
            subtitle = "Action & Strategy Gameplay"
        subtitle = subtitle[:30]

        # Promotional text (<= 170 chars)
        features_str = ", ".join(stats["sample_features"][:3]) if stats["sample_features"] else "streamlined performance and modern design"
        promo = f"Experience {app_name}: crafted for speed, reliability, and security with {features_str}."
        if len(promo) > 170:
            promo = f"Discover {app_name} on Apple platforms: built for performance, security, and intuitive everyday productivity."[:170]

        # Description (<= 4000 chars)
        bullet_list = "\n".join([f"• {feat}" for feat in stats["sample_features"]]) if stats["sample_features"] else "• Intuitive, responsive modern user interface.\n• High-performance native execution.\n• Privacy-first local data architecture."
        desc = (
            f"{app_name} is a native application designed to deliver an exceptional, high-performance experience "
            f"across Apple devices. Engineered with modern Swift technologies, {app_name} empowers users with "
            f"fluid responsiveness, offline-first reliability, and strict privacy protection.\n\n"
            f"Key Capabilities:\n"
            f"{bullet_list}\n\n"
            f"Designed with Apple Human Interface Guidelines:\n"
            f"• Full support for Dark Mode, Dynamic Type, and VoiceOver accessibility.\n"
            f"• Secure local data isolation with zero unauthorized telemetry.\n\n"
            f"Requirements:\n"
            f"• Optimized for modern Apple hardware."
        )

        # Keywords (<= 100 chars)
        base_kw = [app_name.lower(), primary_cat.lower(), secondary_cat.lower()]
        if stats["has_ai"]:
            base_kw.extend(["ai", "automation"])
        if stats["has_health"]:
            base_kw.extend(["health", "workout"])
        if stats["has_game"]:
            base_kw.extend(["arcade", "game"])
        base_kw.extend(["swift", "tools"])
        keywords = ",".join(list(dict.fromkeys(base_kw)))[:100]

        # Review Notes (<= 4000 chars)
        review_notes = (
            f"Dear App Review Team,\n\n"
            f"Thank you for reviewing {app_name}.\n\n"
            f"1. Testing Instructions:\n"
            f"- Launch {app_name}. The main screen grants immediate access to primary features.\n"
            f"- Explore core functionality without requiring any external hardware or mandatory subscription.\n\n"
            f"2. Account Credentials (if applicable):\n"
            f"- A demo review account is pre-configured for testing: appreview@testdemo.apple / DemoPass2026!\n"
            f"- If authentication is requested, select 'Sign in with Demo Account' or proceed as Guest.\n\n"
            f"3. Privacy & Compliance:\n"
            f"- All network requests adhere to secure HTTPS (TLS 1.3). No unauthorized tracking is conducted.\n\n"
            f"Please reach out if you require any additional diagnostic information."
        )

        # Beta Description (<= 4000 chars)
        beta_desc = (
            f"Welcome to the TestFlight beta of {app_name}!\n\n"
            f"What to Test in this Build:\n"
            f"- Core feature flows, UI responsiveness, and navigation stability.\n"
            f"- Visual consistency across Light and Dark Mode.\n"
            f"- Performance and memory efficiency on modern Apple Silicon.\n\n"
            f"Please share your feedback and crash reports directly through TestFlight."
        )

        return {
            "primary_category": primary_cat,
            "secondary_category": secondary_cat,
            "content_rights": content_rights,
            "license_agreement": "Apple Standard End User License Agreement (EULA) applies to all countries and regions.",
            "age_ratings": {"rating": age_rating, "details": age_details},
            "app_encryption_doc": encryption_doc,
            "regulated_medical_devices": reg_medical,
            "routing_coverage": routing_coverage,
            "subtitle": subtitle,
            "promotional_text": promo,
            "description": desc,
            "keywords": keywords,
            "review_notes": review_notes,
            "beta_description": beta_desc,
            "attachment_guidance": "Attach a video walkthrough (walkthrough.mp4) or quick start document (overview.pdf) illustrating core user flows.",
            "demo_credentials": {
                "username": "appreview_demo@developer.apple",
                "password": "ReviewDemoPass2026!",
                "otp_instructions": "2FA is bypassed for App Store Review test accounts."
            },
            "app_purpose": f"Native software engineered to provide {primary_cat.lower()} capabilities with fluid user experience and privacy-first local architecture on Apple platforms."
        }
